### ISSUE TITLE
Update Codeacy to only check code files

### ISSUE THREAD

**Issue by vsoch** [urlstechie/urlchecker-action#49]
I'm not actually sure how to do this, so @SuperKogito it's all you! When you make changes and PR, I'm interested to see how to go about this!

**Comment by SuperKogito** [comment]
well I deactivated Codacy on PRs, so you should not see it from now on. I only kept it for the master.

**Comment by vsoch** [comment]
What would be the workflow for having it on master only?

**Comment by vsoch** [comment]
So when there are codeacy issues, you'll be altered (how?) on merge to master, and then open another PR to fix?

I think if possible we should keep the integration, but only run for a whitelisted set of files, and run on PR.

**Comment by SuperKogito** [comment]
If you click a commit checks (the tiny red X or green mark next to a commit), you will be able to access the logs of codacy, which means you can still take a look at the reports but they won't be in the way when you make a PR.

in case you want to keep it in PRs and know which files you want to run/not run the checks for then I will need a specific list/folder, because I am not sure which ones do you want to whitelist. 


<a href="http://i.imgur.com/Tt63VAc.png">
  <img src="http://imgur.com/Tt63VAcl.png" />
</a>

**Comment by vsoch** [comment]
okay let's do the list - because I would want to know if something is wrong with entrypoint.sh, for example.

 - entrypoint.sh
 - action.yml
 - .github/workflows/main.yml
 - Dockerfile

How's that? Short and sweet!

**Comment by vsoch** [comment]
@SuperKogito and sorry for all the fussing today, I think early in projects there are always a lot of little tweaks and need for updates like this, and the important thing (that I always remember) is that with every change we are moving in the direction of better! :)

**Comment by SuperKogito** [comment]
Okay so that's the list of files to run the checks for right? just to be sure? 
No worries, main thing is that we have a good all around tool that keeps getting better with each release <3

**Comment by SuperKogito** [comment]
okay Codacy will run on PRs but only for the files you mentioned: 

<a href="http://i.imgur.com/twPmbcQ.png">
  <img src="http://imgur.com/twPmbcQl.png" />
</a>

<a href="http://i.imgur.com/NldNbx5.png">
  <img src="http://imgur.com/NldNbx5l.png" />
</a>

I will close this for now. In case this causes problems again, feel free to re-open this ;)
